### ISSUE TITLE
No padding on right panel

### ISSUE THREAD

**Issue by adamberecz** [vueform/builder#34]
### Environment

-

### Reproduction

-

### Describe the bug

Right panel is missing side paddings when used with the following configuration:

```js
{
  leftPanel: ['elements'],
  rightPanel: ['form'],
}
```

**Comment by josh7weaver** [comment]
As a temporary fix in our project I've added this styling in `tailwind.scss` which is only used for vueform so that wherever we render vueform builder we will have the correct padding on the sidebar panel, but obviously its not great to do it that way. I'd be happy to help fix if theres a way to get into the builder code!

```scss
@tailwind base;
@tailwind components;
@tailwind utilities;

// Form Builder
.vfb-panel {
  padding-right: 1.25rem;
  padding-bottom: 1.5rem;
  padding-left: 1.25rem;
}
```

Thanks for creating this bug @adamberecz!
